resource
Label
{
name "multiplayer"
rect 384 0 256 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "multiplayer_b"
}
resource
Label
{
name "multiplayer"
rect 0 0 512 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "multiplayer_a"
}
resource
Label
{
name "Default"
rect 0 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_a.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 384 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_e.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 256 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_b.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 384 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_f.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 256 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_d.tga"
enabledcvar "ui_voodoo"
}

resource
Label
{
name "Default"
rect 0 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/multiplayer_c.tga"
enabledcvar "ui_voodoo"
}

resource
Label
{
name "default"
rect 226 75 64 64
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "NONE"
shader "fan_anim_MP_room"
}

resource
Label
{
name "default"
rect 516 32 64 64
fgcolor 1.00 1.00 1.00 1.00
bgcolor 1.00 1.00 1.00 0.00
borderstyle "NONE"
shader "fan_anim_MP_room2"
}
