resource
Label
{
name "Default"
rect 384 0 256 512
fgcolor 0.00 0.00 0.00 1.00
bgcolor 0.50 0.50 0.50 1.00
borderstyle "RAISED"
shader "serverback_b"
}
resource
Label
{
name "Default"
rect 0 0 512 512
fgcolor 0.00 0.00 0.00 1.00
bgcolor 0.50 0.50 0.50 1.00
borderstyle "RAISED"
shader "serverback_a"
}
resource
Label
{
name "Default"
rect 0 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_a.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 384 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_e.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 256 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_b.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 384 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_f.tga"
enabledcvar "ui_voodoo"

}
resource
Label
{
name "Default"
rect 256 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_d.tga"
enabledcvar "ui_voodoo"
}

resource
Label
{
name "Default"
rect 0 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/serverback_c.tga"
enabledcvar "ui_voodoo"
}

end.
