//all black needed to kick off
resource
Label
{
rect 0 0 640 480
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/black.jpg"
//fadesequence 0 0 360 0
}

//Matt Hall art
resource
Label
{
rect 0 0 640 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission3stat_1.jpg"
fadesequence 2 2.0 2.5 3.0
}


resource
Label
{
rect 350 65 240 320
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/I.jpg"
fadesequence 9.5 2.0 2.5 3.0
}

resource
Label
{
rect 223 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/M.jpg"
fadesequence 17 2.0 5.0 3.0
}

resource
Label
{
rect 464 142 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/L.jpg"
fadesequence 19 2.0 5.0 3.0
}

resource
Label
{
rect 309 307 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/N.jpg"
fadesequence 21 2.0 5.0 3.0
}



resource
Label
{
rect 460 47 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/S.jpg"
fadesequence 29 2.0 5.0 3.0
}

resource
Label
{
rect 300 180 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/C.jpg"
fadesequence 31 2.0 5.5 3.0
}

resource
Label
{
rect 223 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/O.jpg"
fadesequence 36 2.0 4.5 3.0
}

resource
Label
{
rect 304 308 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/G.jpg"
fadesequence 41 2.0 2.5 3.0
}

resource
Label
{
rect 310 57 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/H.jpg"
fadesequence 45.5 2.0 3.0 3.0
}

resource
Label
{
rect 459 308 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/A.jpg"
fadesequence 48.5 2.0 2.5 3.0
}




resource
Label
{
rect 223 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/Q.jpg"
fadesequence 54.0 2.0 4.0 3.0
}


resource
Label
{
rect 392 191 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/R.jpg"
fadesequence 58.0 2.0 3.5 3.0
}




resource
Label
{
rect 350 65 240 320
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/K.jpg"
fadesequence 67.0 2.5 3.5 3.0
}

resource
Label
{
rect 350 65 240 320
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/berlin/Ka.jpg"
fadesequence 74.0 2.0 3.0 3.0
}





resource
Label
{
rect 0 0 640 480
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission3stat_1.jpg"
fadesequence 85.5 2.0 3600.0 3.0
}

