//all black needed to kick off
resource
Label
{
rect 0 0 640 480
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/black.jpg"
//fadesequence 0 0 360 0
}

//Matt Hall art
resource
Label
{
rect 0 0 640 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission2stat_1.jpg"
fadesequence 5 2.0 3.5 3.0
}

resource
Label
{
rect 220 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/A.jpg"
fadesequence 14 2.0 5.5 2.5
}

resource
Label
{
rect 451 144 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/K.jpg"
fadesequence 15 2.0 6.0 3.0
}

resource
Label
{
rect 214 192 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/C.jpg"
fadesequence 16 2.0 6.5 3.5
}



resource
Label
{
rect 220 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/J.jpg"
fadesequence 26 2.0 6.5 2.5
}

resource
Label
{
rect 430 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/F.jpg"
fadesequence 27.5 2.0 6.5 2.5
}

resource
Label
{
rect 306 187 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/L.jpg"
fadesequence 28.5 2.5 6.0 3.0
}

resource
Label
{
rect 474 309 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/M.jpg"
fadesequence 39.5 2.0 4.5 2.5
}

resource
Label
{
rect 319 309 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/O.jpg"
fadesequence 48 2.0 5.0 2.5
}


resource
Label
{
rect 306 49 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/B.jpg"
fadesequence 42 2.0 6.5 2.5
}



//resource
//Label
//{
//rect 214 192 160 120
//fgcolor 1.00 1.00 1.00 1.00
//bgcolor 0.50 0.50 0.50 0.00
//borderstyle NONE
//shader "textures/mohmenu/slideshow/bastogne/G.jpg"
//fadesequence 50 2.0 4.0 2.5
//}



resource
Label
{
rect 306 49 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/D.jpg"
fadesequence 53 2.0 5.5 2.0
}

resource
Label
{
rect 474 309 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/H.jpg"
fadesequence 58 2.0 5.5 3.0
}


resource
Label
{
rect 306 49 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/bastogne/E.jpg"
fadesequence 63 2.0 4.0 3.0
}

resource
Label
{
rect 0 0 640 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission2stat_1.jpg"
fadesequence 73.5 2.0 3600.0 4.0
}






