
//all black needed to kick off
resource
Label
{
rect 0 0 640 480
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/black.jpg"
//fadesequence 0 0 360 0
}

//Matt Hall art
resource
Label
{
rect 0 0 640 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission1stat_1.jpg"
fadesequence 5 2.5 6.5 3.0
}


resource
Label
{
rect 263 159 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/A.jpg"
fadesequence 18 2.0 7.0 3.0
}

resource
Label
{
rect 444 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/U.jpg"
fadesequence 22 2.0 9.0 3.0
}

resource
Label
{
rect 304 192 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/Q.jpg"
fadesequence 30 2.0 8.0 2.0
}

resource
Label
{
rect 237 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/L.jpg"
fadesequence 32 2.0 11.0 3.0
}

resource
Label
{
rect 456 109 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/B.jpg"
fadesequence 42.5 2.0 7 3.0
}

resource
Label
{
rect 213 192 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/M.jpg"
fadesequence 43.5 2.0 8.0 2.5
}

resource
Label
{
rect 438 306 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/D.jpg"
fadesequence 44.5 2.0 9.5 3.0
}


resource
Label
{
rect 274 39 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/V.jpg"
fadesequence 56 2.0 9.0 3.0
}

resource
Label
{
rect 327 309 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/H.jpg"
fadesequence 59 2.0 8.5 3.0
}

resource
Label
{
rect 237 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/T.jpg"
fadesequence 70 2.0 9.5 3.0
}


resource
Label
{
rect 462 126 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/R.jpg"
fadesequence 71 2.0 9.5 3.0
}

resource
Label
{
rect 407 302 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/N.jpg"
fadesequence 72.5 2.0 9.5 3.0
}

resource
Label
{
rect 274 39 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/I.jpg"
fadesequence 85.5 2.0 8.0 3.0
}

resource
Label
{
rect 237 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/O.jpg"
fadesequence 98.5 2.0 3.5 3.0
}

resource
Label
{
rect 315 191 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/S.jpg"
fadesequence 99.5 2.0 6.0 3.0
}

resource
Label
{
rect 444 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/J.jpg"
fadesequence 101 2.0 6.5 3.0
}


resource
Label
{
rect 237 31 160 120
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/C.jpg"
fadesequence 108.5 2.0 6.0 3.0
}

resource
Label
{
rect 315 191 320 240
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/slideshow/normandy/P.jpg"
fadesequence 112 2.0 5.0 3.0
}

resource
Label
{
rect 0 0 640 512
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle NONE
shader "textures/mohmenu/mission1stat_1.jpg"
fadesequence 123 3.0 3600.0 4.0
}
