resource
Label
{
name "Default"
rect 512 256 128 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}
resource
Label
{
name "Default"
rect 256 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}
resource
Label
{
name "Default"
rect 0 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}
resource
Label
{
name "Default"
rect 256 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}
resource
Label
{
name "Default"
rect 512 0 128 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}
resource
Label
{
name "Default"
rect 0 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black

}

resource
Label
{
name "Default"
rect 0 0 640 480
fgcolor 0.20 0.20 0.20 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
shader textures/menu/black
}

end.