
resource
Label
{
name "Default"
rect 384 0 256 512
fgcolor 0.50 0.50 0.50 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "briefingroomdark_b"
}
resource
Label
{
name "Default"
rect 0 0 512 512
fgcolor 0.50 0.50 0.50 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "briefingroomdark_a"
}
resource
Label
{
name "Default"
rect 384 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_c"
enabledcvar "ui_voodoo"
}
resource
Label
{
name "Default"
rect 384 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_f"
enabledcvar "ui_voodoo"
}
resource
Label
{
name "Default"
rect 0 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_a"
enabledcvar "ui_voodoo"
}
resource
Label
{
name "Default"
rect 256 0 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_b"
enabledcvar "ui_voodoo"
}
resource
Label
{
name "Default"
rect 0 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_d"
enabledcvar "ui_voodoo"
}
resource
Label
{
name "Default"
rect 256 256 256 256
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.50 0.50 0.50 0.00
borderstyle "NONE"
shader "textures/mohmenu/voodoo/briefingroomdark_e"
enabledcvar "ui_voodoo"
}

resource
Label
{
name "Default"
rect 184 432 272 40
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.75 0.75 0.75 0.00
borderstyle "NONE"
shader "clickfire"
}
