"""Assemble humanbot/model/shared.json from the fitted parts.

Inputs: humanbot/cache/parts/{keys,spawn,movement,view,trigger,weapon}.json (from the fit_*.py
scripts, git-ignored) and humanbot/model/tuning.json (pooled parameters tuned in
closed loop by calibrate.py, committed). Constants that the recordings cannot fix
(sound noise, belief particle count, ...) are set here and documented.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import hbdata as H  # noqa: E402

MODEL = H.HB_ROOT / "model"


def merge_patch(target, patch):
    """RFC 7386 JSON merge patch."""
    if not isinstance(patch, dict):
        return patch
    if not isinstance(target, dict):
        target = {}
    out = dict(target)
    for k, v in patch.items():
        if v is None:
            out.pop(k, None)
        else:
            out[k] = merge_patch(out.get(k), v)
    return out


def build():
    mv = H.read_part("movement")
    keys = H.read_part("keys")
    spawn = H.read_part("spawn")
    vw = H.read_part("view")
    tr = H.read_part("trigger")
    wp = H.read_part("weapon")
    shared = {
        "version": 1,
        "about": "Pooled human-imitation bot model fitted on the 1v1 SMG duel recordings (all players together). "
                 "Rates are per 50 ms server tick. Generated by humanbot/fit/assemble_model.py; do not edit by hand.",
        "contexts": H.CONTEXTS,
        "chords": H.CHORDS,
        "movement": {
            "keys": {k: keys[k] for k in ["age_edges", "clear_edges", "dist_edges", "ctx_age_edges", "side", "fwd"]},
            "lean": {**{k: mv["lean"][k] for k in ["age_edges", "next", "ctx_age_edges", "ctx_change_logit"]},
                     # The lean's side by the walls beside (fit_movement.fit_lean_wall: -0.41 away from a flat wall,
                     # +0.51 toward an edge just ahead, with the chain as offset) changed the bots' lean little: on
                     # practice-map captures (2026-10-03) their leans in sight went into a flat wall 41% of the time
                     # (people 35%). Three times the fitted wall term brings that to 35%; the edge's pull is set to a
                     # net +2.5 (2.74: around an edge 61%, 3.74: 63%, people 77%; edges a quarter second or longer
                     # 79% vs 76%: people lean toward the opening before they reach it)
                     "wall": {**mv["lean"]["wall"], "wall_logit": round(3.0 * mv["lean"]["wall"]["wall_logit"], 4),
                              "edge_logit": 3.74}},
            "stance": {k: {kk: v[kk] for kk in ["press_hazard", "press_hazard_fire", "hold_pmf", "release_age_edges",
                                                "release_hazard", "up_age_edges", "up_hazard"] if kk in v}
                       for k, v in mv["stance"].items()},
            "veto_clearance": mv["veto_clearance"],
            # the wall reflex (hb_movement.cpp WallAhead) was set in the engine on dm/crnodoors and dm/main:
            # 300 ms brings the bots to the people's wall contact (touching a wall 6-9% of the time, people 6%).
            # How strongly the keys follow the route (nav_*) was set on practice-map captures (2026-10-02,
            # "Encounters" in HANDOFF.md): at 1.0 / 1.5 the bots covered 64 u in 2 s with no enemy part on screen
            # (people 158) and met half as often; 3.0 / 4.5 gives 111 u, more adds little (4.0: 126 u)
            "coupling": {"nav_switch_logit": 3.0, "nav_choice_logit": 4.5, "wall_pressure_logit": 2.0,
                         "wall_reflex_ms": 300.0, "wall_reflex_logit": 4.0},
        },
        "spawn": {k: spawn[k] for k in ["dead_ticks_pmf", "chord_p", "age_edges", "side_switch_p", "fwd_switch_p",
                                         "click_first_p", "click_stay_p", "click_press_p"]},
        "view": {
            "firing": vw["firing"], "idle": vw["idle"], "pitch_firing": vw["pitch_firing"], "pitch_idle": vw["pitch_idle"],
            "flick_deg": vw["flick_deg"],
            # the still gate on the move, and standing (people who stop moving mostly stop turning too)
            "still": {k: vw["still"][k] for k in ["enter", "stay", "enter_standing", "stay_standing", "standing_speed"]},
            "main_sequence": [{k: r[k] for k in ["amp_lo", "amp_med", "ticks_med", "ticks_sigma"]} for r in vw["main_sequence"]],
            # corrective flicks land at 0.84-0.97x the error and overshoot 34-46% of the time (REPORT section 4)
            "flick_gain": {"median": 0.92, "sigma": 0.25},
            "aim_height": {"idle": 0.66, "firing": 0.44, "sd": 0.08},
            "tuning": {"noise_scale": 1.0, "bias_scale": 0.0, "acquire_min_halfw": 1.5, "acquire_hazard": 0.35,
                       "track_flick_hazard": 0.25, "lookaround_per_min": 6.0, "belief_look_share": 0.6, "preaim_share": 0.3, "travel_share": 0.25,
                       "look_dwell_median_ms": 900.0, "look_dwell_sigma": 0.6, "damage_turn_delay_ms": 100.0,
                       # corner pre-aim: people wait a median 1.8 deg onto the cover side of the edge and 2.7 deg below
                       # it 500 ms before the enemy shows (REPORT section 14); how strongly a look decision favours a
                       # corner coming up (weight), how readily a look is broken off for one (hazard) and the horizon
                       # (when an exposure counts as coming up) have no recorded counterpart. calibrate.py tunes them.
                       "preaim_cover_deg": 1.8, "preaim_below_deg": 2.7, "preaim_hazard": 0.1, "preaim_weight": 5.0,
                       "preaim_horizon_ms": 1000.0,
                       # turning onto a corner is a flick from 3 deg off, the smallest turn of the recorded main sequence
                       "preaim_flick_deg": 3.0,
                       # set on practice-map captures: a route behind the view is turned to (people walk backwards 6%
                       # of their hidden time; the bots 10% once their keys followed the route; at 0.2 a tick these
                       # turns, 117 deg at the median, came 11 times a hidden minute and the bots made 18 turns of
                       # 90 deg or more a minute against people's 5), and the respawn of a dead enemy is a new look
                       # decision (people face it within 22 deg 0.5-1 s after it)
                       "route_turn_hazard": 0.05, "respawn_relook": 1.0,
                       # a corner the bot's own motion sweeps past faster than this (deg/s) is passed, not watched:
                       # held at full own-motion compensation, the corners the bots ran past were the largest part of
                       # their hidden view's turning (16 deg/s at the median, people 8). 45 brought it to people's but
                       # halved the view's turn toward the enemy in the last 500 ms before a sighting (10 -> 5 deg,
                       # people 13); 90 keeps three quarters of that turn (practice maps)
                       "preaim_pass_dps": 90.0,
                       # a route look re-aims once the route turned 60 deg (15 chased the path corners: the view turned
                       # 3x as fast as people's while hidden; at 30 the route look still flicked 15 times a hidden minute)
                       "travel_follow_deg": 60.0,
                       # set on practice-map captures (2026-10-03, "Corners and the lost enemy" in HANDOFF.md): right
                       # after losing sight the view holds where the enemy went out of sight (people's view stays 4-5
                       # deg from that spot while the enemy moves on to 10 deg), a watched corner is followed by where
                       # it is whichever exposure offers it, and a belief look watches the corner nearest the believed
                       # position's direction. The crosshair ends closer to the corner than to the enemy at 58% of the
                       # sightings (53% without, people 80%)
                       "lost_aim_last_seen": 1.0, "preaim_follow_geom": 1.0, "belief_look_corner": 1.0,
                       # set on practice-map captures (2026-10-03): an enemy heard behind (footsteps, gunfire more than
                       # 90 deg off the view) is turned to 150 ms after the sound, and that direction is held for 3 s
                       # against route turns, look-arounds and corners (a new sound behind re-aims). People with an
                       # unseen enemy running or firing behind them within 1000 u face it within a second 63% of the
                       # time and are hit first 7%; the bots without the turn 38% and 20%. Held only 0.9 s the view
                       # swung back to the route and turned to the next sound again (60% and 11%, but the hidden view
                       # turned at 16.8 deg/s at the median, 10.6 before, people 8.1); held 3 s: 51%, 13%, 10.3 deg/s
                       "sound_turn_p": 1.0, "sound_turn_delay_ms": 150.0, "sound_turn_hold_ms": 3000.0},
        },
        "trigger": {**{k: tr[k] for k in ["en_edges", "yaw_edges", "lage_los_edges", "lage_hidden_edges", "hold_edges", "gap_edges",
                                           "clip_edges", "press_los", "release_los", "press_hidden", "release_hidden"]},
                    "tuning": {"anticipation_logit": 1.0, "hidden_fire_logit": 0.0, "hidden_late_logit": 0.0}},
        "weapon": {"post_kill_round_edges": wp["post_kill_round_edges"], "post_kill_reload_p": wp["post_kill_reload_p"],
                   "post_kill_delay": wp["post_kill_delay"], "respawn": wp["respawn"],
                   "tactical": wp["tactical"], "pistol_switch_per_min": 0.1},
        # Not measurable in the recordings (no audio, no intent); plan values, tuned by calibrate.py.
        "perception": {"detect_rate": 1.2, "ecc_scale_deg": 18.0, "dist_scale": 1400.0, "part_exponent": 0.7, "loss_memory_ticks": 3,
                       "gunfire_sigma_deg": 10.0, "gunfire_range": 3000.0, "footstep_sigma_deg": 20.0, "footstep_range": 1000.0,
                       "front_back_confusion": 0.25, "reload_range": 600.0, "reload_sigma_deg": 15.0, "distance_log_sd": 0.35,
                       "damage_sigma_deg": 20.0},
        "belief": {"particles": 256, "neg_detect": 0.85, "ess_resample": 0.5, "jitter": 10.0, "move_boost": 1.0,
                   "sound_sigma_scale": 1.0, "spawn_min_dist": 256.0},
        # engage_urgency (the pull toward the enemy for the second after losing sight; none while it is perceived, where
        # the fitted keys and the style dials move the bot) and post_kill_ms (how long a bot stays put after a kill)
        # were set on practice-map captures: in the first second after the enemy left the screen people close in at
        # 31 u/s (urgency 0: 6 u/s; 0.65: 31 u/s), and they run from 0.5 s after a kill (236 u/s, forward held 85%
        # of the time). Pulling in sight too made every bot press forward like the presser family.
        "nav": {"hold_hazard": 0.02, "hold_median_ms": 1500.0, "hold_sigma": 0.7, "spawn_push_ms": 2500.0, "hunt_urgency": 0.8,
                "engage_urgency": 0.65, "reload_urgency": 0.4, "waypoint_reach": 48.0, "repath_ms": 1000.0,
                "post_kill_ms": 500.0},
        "presentation": {"ping_median_ms": 45.0, "ping_sigma": 0.45, "ping_drift_ar": 0.995, "ping_jitter_ms": 4.0,
                         "join_delay_median_ms": 6000.0, "join_delay_sigma": 0.6},
    }
    tuning = MODEL / "tuning.json"
    if tuning.exists():
        shared = merge_patch(shared, json.loads(tuning.read_text()))
    MODEL.mkdir(parents=True, exist_ok=True)
    (MODEL / "shared.json").write_text(json.dumps(H.jsonable(shared), separators=(",", ":")))
    cal = MODEL / "calibration.json"
    if not cal.exists():
        cal.write_text(json.dumps(default_calibration(), indent=1))
    else:
        # a dial new to styles.json gets its placeholder curve until calibrate.py sweeps it
        c = json.loads(cal.read_text())
        dflt = default_calibration()
        missing = [k for k in dflt["dial"] if k not in c.get("dial", {})]
        if missing:
            c.setdefault("dial", {}).update({k: dflt["dial"][k] for k in missing})
            cal.write_text(json.dumps(c, indent=1) + "\n")
            print("calibration.json: placeholder curves for", ", ".join(missing), "(run calibrate.py --stage dials)")
    print("wrote", MODEL / "shared.json", (MODEL / "shared.json").stat().st_size, "bytes")


def default_calibration():
    """Placeholder dial curves (identity-like) until calibrate.py has run."""
    st = json.loads((MODEL / "styles.json").read_text())
    lo, hi, pooled = st["min"], st["max"], st["pooled"]

    def lin(name, y_lo, y_hi):
        return {"x": [lo[name], pooled[name], hi[name]], "y": [y_lo, (y_lo + y_hi) / 2, y_hi]}

    return {
        "version": 1,
        "about": "Monotone curves from a style dial target to the internal offset that realises it. Written by calibrate.py.",
        "dial": {
            "fwd_diag_fight": lin("fwd_diag_fight", -1.5, 1.2),
            "reverse_share": lin("reverse_share", -2.0, 1.5),
            "side_hold_ms": {"x": [lo["side_hold_ms"], pooled["side_hold_ms"], hi["side_hold_ms"]],
                             "y": [lo["side_hold_ms"] / pooled["side_hold_ms"], 1.0, hi["side_hold_ms"] / pooled["side_hold_ms"]]},
            "lean_fight": lin("lean_fight", -1.5, 1.5),
            "jumps_per_min": {"x": [lo["jumps_per_min"], pooled["jumps_per_min"], hi["jumps_per_min"]],
                              "y": [lo["jumps_per_min"] / pooled["jumps_per_min"], 1.0, hi["jumps_per_min"] / pooled["jumps_per_min"]]},
            "crouch_per_min": {"x": [lo["crouch_per_min"], pooled["crouch_per_min"], hi["crouch_per_min"]],
                               "y": [lo["crouch_per_min"] / pooled["crouch_per_min"], 1.0, hi["crouch_per_min"] / pooled["crouch_per_min"]]},
            "walk_hidden": {"x": [lo["walk_hidden"], pooled["walk_hidden"], hi["walk_hidden"]],
                            "y": [lo["walk_hidden"] / pooled["walk_hidden"], 1.0, hi["walk_hidden"] / pooled["walk_hidden"]]},
            "burst_median": lin("burst_median", 0.8, -0.6),
            "aim_height_firing": {"x": [lo["aim_height_firing"], hi["aim_height_firing"]], "y": [lo["aim_height_firing"], hi["aim_height_firing"]]},
            # hold or clear: the log multiplier of the corner pre-aim horizon and of the hold hazard near exposures
            "hold_angle": lin("hold_angle", -1.0, 1.0),
            # the logit shift of a strafe the tick after one is let go
            "counter_strafe": lin("counter_strafe", -1.5, 1.5),
            # the logit shift of a lean switching side when the strafe key turns against it
            "lean_switch": lin("lean_switch", -4.0, 1.0),
            # ... and of letting it go then
            "lean_drop": lin("lean_drop", -0.5, 1.5),
        },
        "skill": {
            "aim_error_fight_deg": {"x": [lo["aim_error_fight_deg"], pooled["aim_error_fight_deg"], hi["aim_error_fight_deg"]],
                                    "y": [lo["aim_error_fight_deg"] / pooled["aim_error_fight_deg"], 1.0,
                                          hi["aim_error_fight_deg"] / pooled["aim_error_fight_deg"]]},
            # press hazard logit with the enemy in sight: faster reactions press sooner
            "reaction_ms": {"x": [lo["reaction_ms"], pooled["reaction_ms"], hi["reaction_ms"]], "y": [0.8, 0.0, -0.8]},
        },
    }


if __name__ == "__main__":
    build()
