"""Assemble humanbot/model/shared.json from the fitted parts.

Inputs: humanbot/cache/parts/{keys,spawn,movement,view,trigger,weapon}.json (from the fit_*.py
scripts, git-ignored) and humanbot/model/tuning.json (pooled parameters tuned in
closed loop by calibrate.py, committed). Constants that the recordings cannot fix
(sound noise, belief particle count, ...) are set here and documented.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import hbdata as H  # noqa: E402

MODEL = H.HB_ROOT / "model"


def merge_patch(target, patch):
    """RFC 7386 JSON merge patch."""
    if not isinstance(patch, dict):
        return patch
    if not isinstance(target, dict):
        target = {}
    out = dict(target)
    for k, v in patch.items():
        if v is None:
            out.pop(k, None)
        else:
            out[k] = merge_patch(out.get(k), v)
    return out


def build():
    mv = H.read_part("movement")
    keys = H.read_part("keys")
    spawn = H.read_part("spawn")
    vw = H.read_part("view")
    tr = H.read_part("trigger")
    wp = H.read_part("weapon")
    shared = {
        "version": 1,
        "about": "Pooled human-imitation bot model fitted on the 1v1 SMG duel recordings (all players together). "
                 "Rates are per 50 ms server tick. Generated by humanbot/fit/assemble_model.py; do not edit by hand.",
        "contexts": H.CONTEXTS,
        "chords": H.CHORDS,
        "movement": {
            "keys": {k: keys[k] for k in ["age_edges", "clear_edges", "dist_edges", "ctx_age_edges", "hid_dist_edges", "side", "fwd"]},
            "lean": {**{k: mv["lean"][k] for k in ["age_edges", "next", "ctx_age_edges", "ctx_change_logit"]},
                     # The lean's side by the walls beside (fit_movement.fit_lean_wall: -0.41 away from a flat wall,
                     # +0.51 toward an edge just ahead, with the chain as offset) changed the bots' lean little: on
                     # practice-map captures (2026-10-03) their leans in sight went into a flat wall 41% of the time
                     # (people 35%). Three times the fitted wall term brings that to 35%; the edge's pull is set to a
                     # net +2.5 (2.74: around an edge 61%, 3.74: 63%, people 77%; edges a quarter second or longer
                     # 79% vs 76%: people lean toward the opening before they reach it)
                     "wall": {**mv["lean"]["wall"], "wall_logit": round(3.0 * mv["lean"]["wall"]["wall_logit"], 4),
                              "edge_logit": 3.74}},
            "stance": {k: {kk: v[kk] for kk in ["press_hazard", "press_hazard_fire", "hold_pmf", "release_age_edges",
                                                "release_hazard", "up_age_edges", "up_hazard"] if kk in v}
                       for k, v in mv["stance"].items()},
            "veto_clearance": mv["veto_clearance"],
            # the wall reflex (hb_movement.cpp WallAhead) was set in the engine on dm/crnodoors and dm/main:
            # 300 ms brings the bots to the people's wall contact (touching a wall 6-9% of the time, people 6%).
            # How strongly the keys follow the route (nav_*) was set on practice-map captures (2026-10-02,
            # "Encounters" in HANDOFF.md): at 1.0 / 1.5 the bots covered 64 u in 2 s with no enemy part on screen
            # (people 158) and met half as often; 3.0 / 4.5 gives 111 u, more adds little (4.0: 126 u).
            # With the enemy hidden the pull grows with its believed distance, x1 within 500 u to x3 from 900 u
            # (nav_far_*), set on captures of all six practice maps (2026-10-04): people run to a far fight (they hold
            # forward 48% of the time with the enemy within 300 u, 80% at 500-1000 u) and the bots, on the longer
            # dm/brownffa and dm/flag, took 7.5-9 s from a spawn to the first sight (people 2.1-2.3); 500-900 u gives
            # 5.6-7 s. Ramped from 300 to 700 u (4.4-6 s) it cost the duel maps, whose hidden fights sit at 250-450 u:
            # the bots stood a third less with the enemy hidden than people and fought more; from 600 to 1000 u the duel
            # maps were the same as now and dm/brownffa lost most of the gain.
            # A key changes for the route when that makes the chord go its way better by more than nav_deadband (the
            # cosine of the angle between the chord and the route), set on practice-map captures (2026-10-05, "Back and
            # forth" in HANDOFF.md): at 0.3 a diagonal or strafe was kept with the route straight ahead (a stable route in
            # the open was within 22 deg of the held chord on 43% of ticks), the bots zig-zagged and, of the 3 s stretches
            # with the enemy hidden in which they ran 300 u, ended within 100 u of the start in 41% (dm/brownffa, dm/flag)
            # and 34% (duel maps; people 9% and 18%); 0.1 with the walls' push on the route halved (g_humanbot_wall_steer)
            # gives 34-37% and 31-35%, 0.0 no more than 0.1, 0.2 half the gain.
            # While the view leads along the way (the view's travel_*), the route pull x travel_pull, set on captures of
            # dm/brownffa and dm/flag (2026-10-05, "Steering with the view" in HANDOFF.md): with the view leading but the
            # pull as before, the bots held a plain strafe 31% of the time they ran on the way (people 15% of their
            # hidden running); x2 and x3 brought the back and forth down by 3 and 4 points.
            # With the enemy believed near and the view on his side (the view's travel_far), the route pull x up to
            # near_pull, by the cosine of the route's angle to the view (a route behind it as fitted), set on practice-map
            # captures (2026-10-05, "Watching his side" in HANDOFF.md): within 700 u of a hidden enemy people hold a forward
            # diagonal where the bots held a plain strafe (with the way 22-67 deg off the view 65% and 9% against 47% and
            # 24%) and ran back and forth three times as often
            "coupling": {"nav_switch_logit": 3.0, "nav_choice_logit": 4.5, "nav_far_mult": 3.0, "nav_far_near": 500.0,
                         "nav_far_dist": 900.0, "nav_deadband": 0.1, "wall_pressure_logit": 2.0, "wall_reflex_ms": 300.0,
                         "wall_reflex_logit": 4.0, "travel_pull": 3.0, "near_pull": 3.0},
        },
        "spawn": {k: spawn[k] for k in ["dead_ticks_pmf", "chord_p", "age_edges", "side_switch_p", "fwd_switch_p",
                                         "click_first_p", "click_stay_p", "click_press_p"]},
        "view": {
            "firing": vw["firing"], "idle": vw["idle"], "pitch_firing": vw["pitch_firing"], "pitch_idle": vw["pitch_idle"],
            "flick_deg": vw["flick_deg"],
            # the still gate on the move, and standing (people who stop moving mostly stop turning too)
            "still": {k: vw["still"][k] for k in ["enter", "stay", "enter_standing", "stay_standing", "standing_speed"]},
            "main_sequence": [{k: r[k] for k in ["amp_lo", "amp_med", "ticks_med", "ticks_sigma"]} for r in vw["main_sequence"]],
            # corrective flicks land at 0.84-0.97x the error and overshoot 34-46% of the time (REPORT section 4)
            "flick_gain": {"median": 0.92, "sigma": 0.25},
            "aim_height": {"idle": 0.66, "firing": 0.44, "sd": 0.08},
            "tuning": {"noise_scale": 1.0, "bias_scale": 0.0, "acquire_min_halfw": 1.5, "acquire_hazard": 0.35,
                       "track_flick_hazard": 0.25, "lookaround_per_min": 6.0, "belief_look_share": 0.6, "preaim_share": 0.3, "travel_share": 0.25,
                       "look_dwell_median_ms": 900.0, "look_dwell_sigma": 0.6, "damage_turn_delay_ms": 100.0,
                       # corner pre-aim: people wait a median 1.8 deg onto the cover side of the edge and 2.7 deg below
                       # it 500 ms before the enemy shows (REPORT section 14); how strongly a look decision favours a
                       # corner coming up (weight), how readily a look is broken off for one (hazard) and the horizon
                       # (when an exposure counts as coming up) have no recorded counterpart. calibrate.py tunes them.
                       "preaim_cover_deg": 1.8, "preaim_below_deg": 2.7, "preaim_hazard": 0.1, "preaim_weight": 5.0,
                       "preaim_horizon_ms": 1000.0,
                       # turning onto a corner is a flick from 3 deg off, the smallest turn of the recorded main sequence
                       "preaim_flick_deg": 3.0,
                       # set on practice-map captures: a route behind the view is turned to (people walk backwards 6%
                       # of their hidden time; the bots 10% once their keys followed the route; at 0.2 a tick these
                       # turns, 117 deg at the median, came 11 times a hidden minute and the bots made 18 turns of
                       # 90 deg or more a minute against people's 5), and the respawn of a dead enemy is a new look
                       # decision (people face it within 22 deg 0.5-1 s after it)
                       "route_turn_hazard": 0.05, "respawn_relook": 1.0,
                       # a corner the bot's own motion sweeps past faster than this (deg/s) is passed, not watched:
                       # held at full own-motion compensation, the corners the bots ran past were the largest part of
                       # their hidden view's turning (16 deg/s at the median, people 8). 45 brought it to people's but
                       # halved the view's turn toward the enemy in the last 500 ms before a sighting (10 -> 5 deg,
                       # people 13); 90 keeps three quarters of that turn (practice maps)
                       "preaim_pass_dps": 90.0,
                       # a route look re-aims once the route turned 60 deg (15 chased the path corners: the view turned
                       # 3x as fast as people's while hidden; at 30 the route look still flicked 15 times a hidden minute)
                       "travel_follow_deg": 60.0,
                       # set on practice-map captures (2026-10-03, "Corners and the lost enemy" in HANDOFF.md): right
                       # after losing sight the view holds where the enemy went out of sight (people's view stays 4-5
                       # deg from that spot while the enemy moves on to 10 deg), a watched corner is followed by where
                       # it is whichever exposure offers it, and a belief look watches the corner nearest the believed
                       # position's direction. The crosshair ends closer to the corner than to the enemy at 58% of the
                       # sightings (53% without, people 80%)
                       "lost_aim_last_seen": 1.0, "preaim_follow_geom": 1.0, "belief_look_corner": 1.0,
                       # set on practice-map captures (2026-10-03): an enemy heard behind (footsteps, gunfire more than
                       # 90 deg off the view) is turned to 150 ms after the sound, and that direction is held for 3 s
                       # against route turns, look-arounds and corners (a new sound behind re-aims). People with an
                       # unseen enemy running or firing behind them within 1000 u face it within a second 63% of the
                       # time and are hit first 7%; the bots without the turn 38% and 20%. Held only 0.9 s the view
                       # swung back to the route and turned to the next sound again (60% and 11%, but the hidden view
                       # turned at 16.8 deg/s at the median, 10.6 before, people 8.1); held 3 s: 51%, 13%, 10.3 deg/s
                       "sound_turn_p": 1.0, "sound_turn_delay_ms": 150.0, "sound_turn_hold_ms": 3000.0,
                       # set on practice-map captures (2026-10-05, "Where the bot looks when first seen" in HANDOFF.md):
                       # footsteps just outside the view (48-90 deg) are turned to as well: people get their view onto an
                       # unseen enemy running there within a second 74-80% of the time against 51-53% for a quiet one,
                       # the bots 70-71% (61-64% quiet); now 80-85%. And a held direction gives way once the enemy is
                       # believed out of view of it: first seen after their spawn people look 5 deg off the enemy at the
                       # median (over 45 deg 4% of lives), the bots 18 deg (25%), most of those with a belief right
                       # within 30 deg but the view held on a direction kept after passing a corner; with both and the
                       # hearing below, 12-13 deg (11%)
                       "sound_turn_deg": 48.0, "hold_belief_deg": 48.0,
                       # set on captures of dm/brownffa and dm/flag (2026-10-05, "Steering with the view" in HANDOFF.md):
                       # travelling with no enemy expected soon (the imminence below 0.2; back below 0.1 after a corner)
                       # the view leads along the way, to the point 200 u ahead on the path (people's view is a median
                       # 20 deg off the way to where they are a second later, and 72% of the time within 30 deg of it).
                       # Its direction follows that point with a quarter of the gap a tick, a turn of more than 45 deg is
                       # one sweep at 0.15 a tick, and the mouse does not rest with the way more than 20 deg off; the
                       # fitted controller turns the view (its yaw error gain x1.5 or x2.5 overshot a 40 deg turn by 20% or
                       # 45% and rang). With the direction followed at once and sweeps from 30 deg at 0.3 the view began a
                       # quick turn 65 times a travel minute (now 50; people's hidden view makes 39 turns of 10 deg or more
                       # a minute there)
                       "travel_lead": 200.0, "travel_imminence": 0.2, "travel_flick_deg": 45.0, "travel_flick_hazard": 0.15,
                       "travel_still_deg": 20.0, "travel_smooth": 0.25,
                       # set on practice-map captures and the owner's game on dm/flag (2026-10-05, "Watching his side" in
                       # HANDOFF.md): the way is led only with the enemy believed further than 800 u (a focused belief;
                       # back past 920). Nearer, people watch his side whichever way they go (within 600 u their view is
                       # 7-25 deg off him even with their way 60-180 deg elsewhere): the corners coming up weigh by their
                       # angle to the believed position (exp(-(d/30)^2)), none over 90 deg off it is watched and a corner,
                       # sound or route look that ends up so far off gives way, a sound is answered on the corner nearest
                       # the believed position when that lies its way, a hidden look is corrected from 4 deg off (0.15 a
                       # tick) and a held direction gives way 20 deg off him. In the owner's game the bot was in the travel
                       # look at 17 of the 40 moments he first had it on screen, its view a median 40 deg off him
                       "travel_far": 800.0, "near_side_deg": 30.0, "near_away_deg": 90.0, "sound_belief_corner": 1.0,
                       "near_reaim_deg": 4.0, "near_reaim_hazard": 0.15, "near_hold_deg": 20.0,
                       # set on captures of dm/flag (2026-10-06, "The crosshair at the door" in HANDOFF.md): a look begun
                       # while the view still turns to the last one is turned to once that turn ends (a quarter of the
                       # hidden looks began so and were left to the idle controller, 21 deg off). With the enemy believed
                       # near, a sound's direction gives way 20 deg off him (after its 600 ms), and there are no
                       # look-arounds and no turns to a route behind the view. Walking into the flag room someone holds, the
                       # bot's view at the moment one first has the other on screen was over 20 deg off him 12-13% of the
                       # time (people 7%), 8-9% with these
                       "look_chain": 1.0, "near_sound_deg": 20.0, "near_lookaround": 0.0, "near_route_turn": 0.0},
        },
        "trigger": {**{k: tr[k] for k in ["en_edges", "yaw_edges", "lage_los_edges", "lage_hidden_edges", "hold_edges", "gap_edges",
                                           "clip_edges", "press_los", "release_los", "press_hidden", "release_hidden"]},
                    # aim_arrive_hw (2026-10-05, "Late aim and low clips" in HANDOFF.md): the press clock in sight restarts at
                    # its peak when the crosshair first comes within 2 body half-widths of the enemy later in a sighting.
                    # People whose aim gets there 0.3-1.5 s in press at 20-38% a tick in the next 250 ms, as early as any;
                    # the fitted clock runs from the parts on screen (people's aim is there by 0.3 s in nine sightings in
                    # ten), and a bot slow to get there tracked the owner for seconds at 1-2% a tick
                    "tuning": {"anticipation_logit": 1.0, "hidden_fire_logit": 0.0, "hidden_late_logit": 0.0,
                               "aim_arrive_hw": 2.0}},
        "weapon": {"post_kill_round_edges": wp["post_kill_round_edges"], "post_kill_reload_p": wp["post_kill_reload_p"],
                   "post_kill_delay": wp["post_kill_delay"], "respawn": wp["respawn"],
                   "tactical": wp["tactical"], "pistol_switch_per_min": 0.1},
        # Not measurable in the recordings (no audio, no intent); plan values, tuned by calibrate.py. Except the
        # front/back confusion of footsteps (the plan's 0.25): people hear which side an enemy runs on. With an unseen
        # enemy running in front of them within 1000 u they turn around within a second 2.4% of the time, no more than
        # with a quiet one (3.1%), and face one running behind them 69% (quiet 33%). With a quarter of the footsteps
        # heard on the mirrored side the bots turned around 11% (practice maps, 2026-10-05); with none, 2.7%.
        # The soft wallhack (the owner's, 2026-10-05: experienced players nearly always know where their opponent is): a
        # hidden enemy's direction reaches the belief 40 times a minute, 25 deg and a log-normal 0.35 off, never the view.
        # With the view on the side of an enemy believed near (the view's travel_far) the bots' belief was 100 deg off
        # him at the sightings where he caught them looking the other way (over 90 deg off 10% of the times he first had
        # them on screen, 8% before; people 3%): with the hunch 8% (duel maps and dm/brownffa, dm/flag; "Watching his
        # side" in HANDOFF.md)
        "perception": {"detect_rate": 1.2, "ecc_scale_deg": 18.0, "dist_scale": 1400.0, "part_exponent": 0.7, "loss_memory_ticks": 3,
                       "gunfire_sigma_deg": 10.0, "gunfire_range": 3000.0, "footstep_sigma_deg": 20.0, "footstep_range": 1000.0,
                       "front_back_confusion": 0.0, "reload_range": 600.0, "reload_sigma_deg": 15.0, "distance_log_sd": 0.35,
                       "damage_sigma_deg": 20.0, "hunch_per_min": 40.0, "hunch_sigma_deg": 25.0, "hunch_dist_log_sd": 0.35},
        "belief": {"particles": 256, "neg_detect": 0.85, "ess_resample": 0.5, "jitter": 10.0, "move_boost": 1.0,
                   "sound_sigma_scale": 1.0, "spawn_min_dist": 256.0},
        # engage_urgency (the pull toward the enemy for the second after losing sight; none while it is perceived, where
        # the fitted keys and the style dials move the bot) and post_kill_ms (how long a bot stays put after a kill)
        # were set on practice-map captures: in the first second after the enemy left the screen people close in at
        # 31 u/s (urgency 0: 6 u/s; 0.65: 31 u/s), and they run from 0.5 s after a kill (236 u/s, forward held 85%
        # of the time). Pulling in sight too made every bot press forward like the presser family.
        "nav": {"hold_hazard": 0.02, "hold_median_ms": 1500.0, "hold_sigma": 0.7, "spawn_push_ms": 2500.0, "hunt_urgency": 0.8,
                "engage_urgency": 0.65, "reload_urgency": 0.4, "waypoint_reach": 48.0, "repath_ms": 1000.0,
                "post_kill_ms": 500.0,
                # in a fight with under a quarter of the clip left the bot makes for cover at the reload urgency (set on
                # practice-map captures, 2026-10-05): in sight with that little people are out of the enemy's sight
                # 1-1.5 s later 54-59% of the time (30-35% with more), the bots 20-38%, and the bots began five times
                # as many reloads in the enemy's view (1.6 a minute alive against 0.3); now 31-46% and 1.3. Twice the
                # urgency did no better
                "low_clip_cover": 0.25,
                # On a map with a recorded prior the engine's path goes to a point via_dist along the route over the
                # cells and moves people made, not straight to the goal (set on practice-map captures, 2026-10-05, "The
                # way people go" in HANDOFF.md): the navmesh's shortest way on dm/flag runs round the ring through Door
                # 2, past the Railing and through Door 3, where people never go (the bots 11% of their time there, in
                # the owner's game the bot 18% in the Door 2 corridor, the owner 3%)
                "via_dist": 384.0},
        "presentation": {"ping_median_ms": 45.0, "ping_sigma": 0.45, "ping_drift_ar": 0.995, "ping_jitter_ms": 4.0,
                         "join_delay_median_ms": 6000.0, "join_delay_sigma": 0.6},
    }
    tuning = MODEL / "tuning.json"
    if tuning.exists():
        shared = merge_patch(shared, json.loads(tuning.read_text()))
    MODEL.mkdir(parents=True, exist_ok=True)
    (MODEL / "shared.json").write_text(json.dumps(H.jsonable(shared), separators=(",", ":")))
    cal = MODEL / "calibration.json"
    if not cal.exists():
        cal.write_text(json.dumps(default_calibration(), indent=1))
    else:
        # a dial new to styles.json gets its placeholder curve until calibrate.py sweeps it
        c = json.loads(cal.read_text())
        dflt = default_calibration()
        missing = [k for k in dflt["dial"] if k not in c.get("dial", {})]
        if missing:
            c.setdefault("dial", {}).update({k: dflt["dial"][k] for k in missing})
            cal.write_text(json.dumps(c, indent=1) + "\n")
            print("calibration.json: placeholder curves for", ", ".join(missing), "(run calibrate.py --stage dials)")
    print("wrote", MODEL / "shared.json", (MODEL / "shared.json").stat().st_size, "bytes")


def default_calibration():
    """Placeholder dial curves (identity-like) until calibrate.py has run."""
    st = json.loads((MODEL / "styles.json").read_text())
    lo, hi, pooled = st["min"], st["max"], st["pooled"]

    def lin(name, y_lo, y_hi):
        return {"x": [lo[name], pooled[name], hi[name]], "y": [y_lo, (y_lo + y_hi) / 2, y_hi]}

    return {
        "version": 1,
        "about": "Monotone curves from a style dial target to the internal offset that realises it. Written by calibrate.py.",
        "dial": {
            "fwd_diag_fight": lin("fwd_diag_fight", -1.5, 1.2),
            "reverse_share": lin("reverse_share", -2.0, 1.5),
            "side_hold_ms": {"x": [lo["side_hold_ms"], pooled["side_hold_ms"], hi["side_hold_ms"]],
                             "y": [lo["side_hold_ms"] / pooled["side_hold_ms"], 1.0, hi["side_hold_ms"] / pooled["side_hold_ms"]]},
            "lean_fight": lin("lean_fight", -1.5, 1.5),
            "jumps_per_min": {"x": [lo["jumps_per_min"], pooled["jumps_per_min"], hi["jumps_per_min"]],
                              "y": [lo["jumps_per_min"] / pooled["jumps_per_min"], 1.0, hi["jumps_per_min"] / pooled["jumps_per_min"]]},
            "crouch_per_min": {"x": [lo["crouch_per_min"], pooled["crouch_per_min"], hi["crouch_per_min"]],
                               "y": [lo["crouch_per_min"] / pooled["crouch_per_min"], 1.0, hi["crouch_per_min"] / pooled["crouch_per_min"]]},
            "walk_hidden": {"x": [lo["walk_hidden"], pooled["walk_hidden"], hi["walk_hidden"]],
                            "y": [lo["walk_hidden"] / pooled["walk_hidden"], 1.0, hi["walk_hidden"] / pooled["walk_hidden"]]},
            "burst_median": lin("burst_median", 0.8, -0.6),
            "aim_height_firing": {"x": [lo["aim_height_firing"], hi["aim_height_firing"]], "y": [lo["aim_height_firing"], hi["aim_height_firing"]]},
            # hold or clear: the log multiplier of the corner pre-aim horizon and of the hold hazard near exposures
            "hold_angle": lin("hold_angle", -1.0, 1.0),
            # the logit shift of a strafe the tick after one is let go
            "counter_strafe": lin("counter_strafe", -1.5, 1.5),
            # the logit shift of a lean switching side when the strafe key turns against it
            "lean_switch": lin("lean_switch", -4.0, 1.0),
            # ... and of letting it go then
            "lean_drop": lin("lean_drop", -0.5, 1.5),
        },
        "skill": {
            "aim_error_fight_deg": {"x": [lo["aim_error_fight_deg"], pooled["aim_error_fight_deg"], hi["aim_error_fight_deg"]],
                                    "y": [lo["aim_error_fight_deg"] / pooled["aim_error_fight_deg"], 1.0,
                                          hi["aim_error_fight_deg"] / pooled["aim_error_fight_deg"]]},
            # press hazard logit with the enemy in sight: faster reactions press sooner
            "reaction_ms": {"x": [lo["reaction_ms"], pooled["reaction_ms"], hi["reaction_ms"]], "y": [0.8, 0.0, -0.8]},
        },
    }


if __name__ == "__main__":
    build()
