#!/usr/bin/env python3
"""Generate code/humanbot/hb_embedded.cpp from humanbot/model/*.json and humanbot/maps/*.json.

The JSON texts are embedded byte for byte as arrays of short string literals (MSVC
limits a single literal to ~16 KB). The SHA-256 of the bundle is computed over
"name\\ntext\\n" for every file in name order and written into the source; the
runtime reports it in the telemetry metadata.

Usage: embed_model.py [--check]   (--check: exit 1 if the generated file is stale)
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HB = ROOT / "humanbot"
OUT = ROOT / "code" / "humanbot" / "hb_embedded.cpp"
CHUNK = 3000

HEADER = """/*
===========================================================================
Copyright (C) 2026 the OpenMoHAA team

This file is part of OpenMoHAA source code.

OpenMoHAA source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

OpenMoHAA source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenMoHAA source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
// hb_embedded.cpp: GENERATED by humanbot/tools/embed_model.py. Do not edit.
"""


def files():
    out = []
    for p in sorted((HB / "model").glob("*.json")):
        if p.name == "tuning.json":
            continue  # already merged into shared.json by assemble_model.py
        out.append((p.name, p.read_text(encoding="utf-8")))
    for p in sorted((HB / "maps").glob("*.json")):
        out.append(("maps/" + p.name, p.read_text(encoding="utf-8")))
    return sorted(out)


def bundle_sha(fs):
    h = hashlib.sha256()
    for name, text in fs:
        h.update(name.encode() + b"\n" + text.encode("utf-8") + b"\n")
    return h.hexdigest()


def c_literal(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "?":
            out.append("\\?")  # no trigraphs
        elif 32 <= o < 127:
            out.append(ch)
        else:
            for b in ch.encode("utf-8"):
                out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def generate():
    fs = files()
    lines = [HEADER, '#include "hb_bundle.h"', "", "namespace hb", "{", "", "namespace", "{", ""]
    table = []
    for i, (name, text) in enumerate(fs):
        ident = "k_file_%d" % i
        chunks = [text[k:k + CHUNK] for k in range(0, len(text), CHUNK)] or [""]
        lines.append("// %s (%d bytes)" % (name, len(text.encode("utf-8"))))
        lines.append("const char *const %s[] = {" % ident)
        for c in chunks:
            lines.append("    %s," % c_literal(c))
        lines.append("};")
        lines.append("")
        table.append((name, ident, len(chunks)))
    lines.append("struct EmbeddedFile {")
    lines.append("    const char        *name;")
    lines.append("    const char *const *chunks;")
    lines.append("    int                count;")
    lines.append("};")
    lines.append("")
    lines.append("const EmbeddedFile k_files[] = {")
    for name, ident, n in table:
        lines.append('    {"%s", %s, %d},' % (name, ident, n))
    lines.append("};")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::string EmbeddedText(const std::string& name)")
    lines.append("{")
    lines.append("    for (const EmbeddedFile& f : k_files) {")
    lines.append("        if (name == f.name) {")
    lines.append("            std::string text;")
    lines.append("            for (int i = 0; i < f.count; i++) {")
    lines.append("                text += f.chunks[i];")
    lines.append("            }")
    lines.append("            return text;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return std::string();")
    lines.append("}")
    lines.append("")
    lines.append("std::vector<std::string> EmbeddedNames()")
    lines.append("{")
    lines.append("    std::vector<std::string> names;")
    lines.append("    for (const EmbeddedFile& f : k_files) {")
    lines.append("        names.push_back(f.name);")
    lines.append("    }")
    lines.append("    return names;")
    lines.append("}")
    lines.append("")
    lines.append("const char *EmbeddedSha256()")
    lines.append("{")
    lines.append('    return "%s";' % bundle_sha(fs))
    lines.append("}")
    lines.append("")
    lines.append("} // namespace hb")
    lines.append("")
    return "\n".join(lines)


def main():
    src = generate()
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != src:
            print("hb_embedded.cpp is stale: run humanbot/tools/embed_model.py", file=sys.stderr)
            return 1
        print("hb_embedded.cpp is in sync (%s)" % bundle_sha(files()))
        return 0
    OUT.write_text(src, encoding="utf-8")
    print("wrote", OUT, OUT.stat().st_size, "bytes, sha256", bundle_sha(files()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
